### ISSUE TITLE
Animation [User is typing]

### ISSUE THREAD

**Issue by apenasigordev** [skyra-project/discord-components#112] opened 2021-08-20 11:54 UTC
Is it possible in the future to be created [User is typing]? I was thinking about doing this, but I think it might take a long time to do, even though I have this "problem" I really want to create this 'update'

**Comment by Favna** [comment] 2021-08-22 11:52
@Snazzah do you think you could do this one as well, maybe?

**Comment by apenasigordev** [comment] 2021-08-22 11:53
I think this idea is cool

**Comment by Snazzah** [comment] 2021-10-02 19:02
@Favna Sure, but where would this be in terms of what components we have now? It would be out of place to add a typing indicator straight into `<discord-messages>`.

**Comment by Favna** [comment] 2021-10-02 21:21
That's actually a good question. I can't think of a good solution. @apenasigordev do you know something?

**Comment by apenasigordev** [comment] 2021-10-03 02:37
You can put in `<discord-messages>` with a component written `<discord-typing author="User"/>`

**Comment by Favna** [comment] 2021-10-03 09:55
> You can put in `<discord-messages>` with a component written `<discord-typing author="User"/>`

Thats not what we're asking. The problem is that discord messages are messages, but "user is typing" is an animation that shows below the chat input bar and outside of the context of any message.

**Comment by favna** [comment] 2021-12-22 19:58
I'm going to close this because as far as I know this isn't feasible because of previously mentioned reasons. Feel free to re-open if you come up with how we can tackle this.

**Closed by favna** 2021-12-22 19:58 UTC

**Comment by apenasigordev** [comment] 2021-12-22 20:10
> I'm going to close this because as far as I know this isn't feasible because of previously mentioned reasons. Feel free to re-open if you come up with how we can tackle this.

ok ty
